spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    database: H2
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2-console
    devtools:
      restart:
        enabled: true
      livereload:
        enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
      serialization.indent_output: true
  datasource:
    database-platform: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    hikari:
      auto-commit: false

server:
  servlet:
    context-path: /refapp
  port: 8001


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
