spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://spdb.cs798li7xuhn.us-east-2.rds.amazonaws.com:3306/sp_accountapp;?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: appuser
    password: appuser
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

server:
  servlet:
    context-path: /accountapp
  port: 8080

logging:
  level:
    ROOT: INFO
    net.sp.referenceapp: INFO

