CREATE TABLE ACCOUNTS (
	id varchar(255) not null,
	username varchar(255) not null,
	password varchar(255) not null,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	contact varchar(255),
	ssn varchar(255) not null,
	created_by varchar(255),
	last_modified_by varchar(255),
	created_date TIMESTAMP,
	last_modified_date TIMESTAMP
	
);


CREATE TABLE SP_AUDIT_EVENT (
	event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	principal varchar(255) not null,
	event_type varchar(255) not null,
	event_date TIMESTAMP
	
);

CREATE TABLE sp_audit_evt_data (
	event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255),
	value varchar(255) 
);